# Generated by Django 4.1.7 on 2023-12-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
