# Generated by Django 4.1.7 on 2023-12-28 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0004_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='category_id',
        ),
        migrations.AddField(
            model_name='ads',
            name='category_id',
            field=models.ManyToManyField(to='Core.category'),
        ),
    ]
