# Generated by Django 4.1.7 on 2024-01-01 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_rename_image_category_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.ManyToManyField(to='Core.category'),
        ),
        migrations.RemoveField(
            model_name='ads',
            name='category_id',
        ),
        migrations.AddField(
            model_name='ads',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Core.category'),
        ),
    ]
