# Generated by Django 4.1.7 on 2024-01-01 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_company_category_remove_ads_category_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='image',
        ),
        migrations.AddField(
            model_name='company',
            name='icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
