# Generated by Django 4.1.7 on 2024-01-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0008_remove_company_image_company_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='icon',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='icon',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='company',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='category_id',
        ),
        migrations.AddField(
            model_name='ads',
            name='category_id',
            field=models.ManyToManyField(to='Core.category'),
        ),
    ]
