# Generated by Django 4.1.7 on 2024-01-03 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_rename_icon_category_image_rename_icon_company_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='likes_count',
            new_name='views_count',
        ),
    ]
