# Generated by Django 4.1.7 on 2024-01-22 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0011_ads_slug_category_slug_company_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='info',
            new_name='responsibilities',
        ),
    ]
