# Generated by Django 4.1.7 on 2024-01-22 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0012_rename_info_ads_responsibilities'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ads',
            old_name='condition',
            new_name='conditions',
        ),
    ]
