# Generated by Django 4.1.7 on 2024-01-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0013_rename_condition_ads_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
